# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00474b9493ae6f23f756bbdb28ba7138ee2b90e7760d91246ba9b1af79341490cd730561eb4bf9b8a2dde25e26a7e429693a3dc695650f5b9ff1c8eda3a3bbf2

test:
  secret_key_base: 0dc0a5c1f201366f33dec54860fd14315efe5b2477d890854a5723f819928114dd5a57ee553e8f279e406e4544a48f9924f5f9ec61dfd84db58b1d2e99c380af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
